/** Central route paths — single source of truth for navigation & redirects */
export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  app: {
    root: "/app",
    dashboard: "/app/dashboard",
    dataInput: "/app/data-input",
    dataInputStep1: "/app/data-input/step-1",
    dataInputStep2: "/app/data-input/step-2",
    dataInputStep3: "/app/data-input/step-3",
    uploadDoc: "/app/documents/upload",
    aiReview: "/app/documents/ai-review",
    emissionDetail: "/app/emissions/detail",
    ecoScore: "/app/eco-score",
    recommendations: "/app/recommendations",
    reports: "/app/reports",
    company: "/app/company",
    settings: "/app/settings",
    account: "/app/account",
    changePassword: "/app/account/change-password",
    businesses: "/app/businesses",
    businessCreate: "/app/businesses/new",
    businessDetail: (id: string) => `/app/businesses/${id}`,
    businessEdit: (id: string) => `/app/businesses/${id}/edit`,
    businessMembers: (id: string) => `/app/businesses/${id}/members`,
  },
} as const;
