import type { BusinessStatus } from "@/features/businesses/types/businesses.types";

export const BUSINESS_STATUS_LABELS: Record<BusinessStatus, string> = {
  ACTIVE: "Đang hoạt động",
  SUSPENDED: "Tạm ngưng",
  ARCHIVED: "Lưu trữ",
};

export const BUSINESS_STATUS_OPTIONS: { value: BusinessStatus; label: string }[] =
  [
    { value: "ACTIVE", label: BUSINESS_STATUS_LABELS.ACTIVE },
    { value: "SUSPENDED", label: BUSINESS_STATUS_LABELS.SUSPENDED },
    { value: "ARCHIVED", label: BUSINESS_STATUS_LABELS.ARCHIVED },
  ];

export const BUSINESSES_COPY = {
  nav: "Doanh nghiệp",
  list: {
    breadcrumbs: [{ label: "Doanh nghiệp", active: true }],
    title: "Doanh nghiệp",
    description:
      "Quản lý danh sách doanh nghiệp bạn tham gia, tìm kiếm và lọc theo trạng thái.",
    createCta: "Thêm doanh nghiệp",
    searchPlaceholder: "Tìm theo tên hoặc mã…",
    filterAll: "Tất cả trạng thái",
    loading: "Đang tải danh sách…",
    error: "Không tải được danh sách doanh nghiệp. Vui lòng thử lại.",
    empty: "Chưa có doanh nghiệp nào.",
    emptyFiltered: "Không tìm thấy doanh nghiệp phù hợp.",
    columns: {
      name: "Doanh nghiệp",
      taxCode: "Mã số thuế",
      industry: "Ngành",
      status: "Trạng thái",
      actions: "Thao tác",
    },
    view: "Xem",
    edit: "Sửa",
    delete: "Xoá",
    pagination: {
      summary: (from: number, to: number, total: number) =>
        `${from}–${to} trên ${total}`,
      prev: "Trước",
      next: "Sau",
      page: (page: number, total: number) => `Trang ${page}/${total}`,
    },
    noValue: "—",
  },
  detail: {
    breadcrumbs: [{ label: "Doanh nghiệp" }, { label: "Chi tiết", active: true }],
    back: "Quay lại danh sách",
    edit: "Chỉnh sửa",
    delete: "Xoá doanh nghiệp",
    loading: "Đang tải doanh nghiệp…",
    error: "Không tải được thông tin doanh nghiệp.",
    infoTitle: "Thông tin chung",
    metaTitle: "Thông tin hệ thống",
    fields: {
      name: "Tên doanh nghiệp",
      slug: "Đường dẫn (slug)",
      taxCode: "Mã số thuế",
      industry: "Ngành nghề",
      country: "Quốc gia",
      timezone: "Múi giờ",
      website: "Website",
      status: "Trạng thái",
      createdAt: "Ngày tạo",
      updatedAt: "Cập nhật lần cuối",
    },
    deleteConfirm: (name: string) =>
      `Xoá doanh nghiệp "${name}"? Hành động này không thể hoàn tác.`,
  },
  form: {
    createBreadcrumbs: [
      { label: "Doanh nghiệp" },
      { label: "Thêm mới", active: true },
    ],
    editBreadcrumbs: [
      { label: "Doanh nghiệp" },
      { label: "Chỉnh sửa", active: true },
    ],
    createTitle: "Thêm doanh nghiệp",
    createDescription:
      "Tạo doanh nghiệp mới và gửi lời mời cho quản trị viên doanh nghiệp.",
    editTitle: "Chỉnh sửa doanh nghiệp",
    editDescription: "Cập nhật thông tin doanh nghiệp.",
    sectionGeneral: "Thông tin doanh nghiệp",
    sectionAdmin: "Quản trị viên doanh nghiệp",
    sectionBranch: "Chi nhánh mặc định (tuỳ chọn)",
    labels: {
      name: "Tên doanh nghiệp",
      slug: "Đường dẫn (slug)",
      taxCode: "Mã số thuế",
      industry: "Ngành nghề",
      country: "Quốc gia (mã 2 ký tự)",
      timezone: "Múi giờ",
      website: "Website",
      status: "Trạng thái",
      companyAdminEmail: "Email quản trị viên",
      companyAdminFullName: "Họ tên quản trị viên",
      branchName: "Tên chi nhánh",
      branchCode: "Mã chi nhánh",
      branchAddress: "Địa chỉ",
      branchCountry: "Quốc gia chi nhánh",
    },
    placeholders: {
      name: "VD: Công ty TNHH ABC",
      slug: "vd-cong-ty-abc",
      taxCode: "0312345678",
      industry: "Sản xuất, Bán lẻ…",
      country: "VN",
      timezone: "Asia/Ho_Chi_Minh",
      website: "https://congty.vn",
      companyAdminEmail: "admin@congty.vn",
      companyAdminFullName: "Nguyễn Văn A",
      branchName: "Trụ sở chính",
      branchCode: "HQ",
      branchAddress: "Số 1, Đường ABC, Quận 1",
      branchCountry: "VN",
    },
    submitCreate: "Tạo doanh nghiệp",
    submitEdit: "Lưu thay đổi",
    submitting: "Đang lưu…",
    cancel: "Huỷ",
    createSuccess: "Tạo doanh nghiệp thành công.",
    editSuccess: "Cập nhật doanh nghiệp thành công.",
    adminOnly: "Chỉ quản trị viên hệ thống mới có thể tạo doanh nghiệp.",
    loading: "Đang tải doanh nghiệp…",
    notFound: "Không tìm thấy doanh nghiệp.",
  },
  validation: {
    nameRequired: "Vui lòng nhập tên doanh nghiệp.",
    nameMin: "Tên tối thiểu 2 ký tự.",
    slugRequired: "Vui lòng nhập đường dẫn (slug).",
    slugInvalid: "Slug chỉ gồm chữ thường, số và dấu gạch ngang.",
    countryLength: "Mã quốc gia gồm 2 ký tự.",
    emailRequired: "Vui lòng nhập email quản trị viên.",
    emailInvalid: "Email không hợp lệ.",
    websiteInvalid: "Website không hợp lệ.",
  },
} as const;
